version: "3"
services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example2
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db
      - ./mongo/init:/docker-entrypoint-initdb.d/

  nextjs:
    build:
      context: ./docker/construct_app
      dockerfile: Dockerfile-app
    container_name: n-app
    ports:
      - 3000:3000
    volumes: # mount workdir
      - ./app:/src
    command: sh -c "npm install && npm run dev"
    environment:
      CHOKIDAR_USEPOLLING: "true"

  # https-portal:
  #   image: steveltn/https-portal:1
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   environment:
  #     DOMAINS: "gcp.kyuki3rain.com -> http://nextjs:3000"
  #     STAGE: "production"
  #     # FORCE_RENEW: "true"

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example2
    depends_on:
      - mongo

volumes:
  mongodata:
