version: "3"
services:
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - "80:80"
      - "443:443"
    restart: always
    environment:
      DOMAINS: "gcp.kyuki3rain.com -> http://web:8000"
      STAGE: "production"
      # FORCE_RENEW: "true"

  web:
    build:
      context: ./docker/construct_web
      dockerfile: Dockerfile-web
    image: nn-web # docker image name
    container_name: nn-web # docker container name
    ports:
      - 8000:8000

  nextjs:
    build:
      context: ./docker/construct_app
      dockerfile: Dockerfile-app
    container_name: n-app
    ports:
      - 3000:3000
    volumes: # mount workdir
      - ./app:/src
    command: sh -c "npm install && yarn dev"
