version: "3"
services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example2
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db
      - ./mongo/init:/docker-entrypoint-initdb.d/

  nextjs:
    build:
      context: ./docker/construct_app
      dockerfile: Dockerfile-app
    container_name: n-app
    ports:
      - 3000:3000
    volumes:
      - ./prev_app:/src
    command: sh -c "npm install && npm start"
    environment:
      CHOKIDAR_USEPOLLING: "true"

  web:
    build:
      context: ./docker/construct_web
      dockerfile: Dockerfile-web
    image: nn-web # docker image name
    container_name: nn-web # docker container name
    ports:
      - 8000:8000

  https-portal:
    image: steveltn/https-portal:1
    ports:
      - "80:80"
      - "443:443"
    environment:
      DOMAINS: "kyuki3rain.com -> http://web:8000"
      STAGE: "production"
      # FORCE_RENEW: "true"

volumes:
  mongodata:
